AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - spec/**/*.rb
  Exclude:
    - db/**/*.rb
    - bin/**/*
    - vendor/**/*
Style/FileName:
  Exclude:
    - Gemfile
Rails:
  Enabled: true
