sudo: false
language: ruby
rvm:
  - 2.4.1
before_install:
  - gem install bundler
  - bundle install
  - bundle exec rails db:setup
script:
  - bundle exec rake test && bundle exec codeclimate-test-reporter
