sudo: false
language: ruby
cache: bundler
bundler_args: --deployment --without development
services:
  - postgresql
rvm:
  - 2.6.3
before_install:
  - gem update --system
  - bundle update --bundler
before_script:
  - bundle exec rails db:setup
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
